### ISSUE TITLE
[iOS] 메인화면 구현 

### ISSUE THREAD

**Issue by JooYoung1121** [Naver-Children-StudyRoom/service-issue#10]
# 메인화면 

### 비로그인 상황
1. 각 기능별 설명 ScrollView 
2. 기능에 대한 View이미지와 설명 위치가 전부 다른거 감안해야함 
3. 기능마다 자세히알아보기 버튼 만들고 튜토리얼(서비스소개)화면으로 이동 구현 
4. 맨 아래로 스크롤 시 로그인 버튼 노출 
### 로그인 상황 
1. 탭바 노출 (서비스소개, 독서실 둘러보기, 플래너, 마이페이지)
2. 로그아웃 기능 구현 
3. 나의 독서실 요약 View구현 
4. 마이플래너 요약 구현 
5. 독서실 추천? -> 가장 최근에 생성되었거나 내가 최근에 접속했던 독서실 보여주면 될 듯 
6. 서비스 소개 클릭 시 탭바가 노출되는 상태로 서비스소개화면 노출

### 비로그인 상황
- [x] 각 기능에 대한 설명을 보여주는 ScrollView 구현 
- [x] 스크롤시 나오는 뷰에 해당하는 버튼 구현 
- [x] 로그인 View로 이동하는 버튼 구현 
- [x] 튜토리얼(서비스소개) View 구현 -> 로그인/비로그인 구분 
### 로그인 상황 
- [x] 탭바 노출 (서비스소개, 독서실 둘러보기, 플래너, 마이페이지) 
- [x] 로그아웃 기능 구현 
- [x] 나의 독서실 요약, 마이플래너, 추천 독서실 더미데이터 생성
- [x] 나의 독서실 요약, 마이플래너, 추천독서실 View 구현 

## 고려할 사항 
- 로그인/비로그인 시 탭바를 숨길지 터치가 안되도록 할지 고민
- 로그인 한번이라도 하면 토큰에 맞게 쭉 로그인 상태로 유지되야할지
