### ISSUE TITLE
[공통] 각 기능별 마일스톤 설정 

### ISSUE THREAD

**Issue by JooYoung1121** [Naver-Children-StudyRoom/service-issue#9]
# Client (FE)
- [ ] 1. 메인화면 View 구현
- [ ] 2. 로그인화면/회원가입/마이페이지 View 구현 
- [ ] 3. 구현된 기능들에 대한 API 연동
- [ ] 4. 독서실 둘러보기 View 구현 및 API 연동
- [ ] 5. 독서실 만들기 View 구현 및 API연동 
- [ ] 6. 플래너 View 구현 및 API연동
- [ ] 7. 독서실 내부 기능 구현

# Client (iOS)
- [ ] 1. 메인화면 View 구현
- [ ] 2. 로그인화면/회원가입/마이페이지 View 구현 
- [ ] 3. 구현된 기능들에 대한 API 연동
- [ ] 4. 독서실 둘러보기 View 구현 및 API 연동
- [ ] 5. 독서실 만들기 View 구현 및 API연동 
- [ ] 6. 플래너 View 구현 및 API연동
- [ ] 7. 독서실 내부 기능 구현

# Server 
- [ ] 1. 디비설계 및 서버구축 
- [ ] 2. 로그인, 회원가입, 마이페이지에 대한 API 인터페이스 구성 및 구현 
- [ ] 3. 독서실 둘러보기 구현
- [ ] 4. 독서실 만들기 구현
- [ ] 5. 플래너 구현
- [ ] 6. 독서실 구현 

## 세부 내용 
- 3월 16일 기준으로 카운팅 시작 
- Client는 3번까지 8주 내로 진행 
- Server는 2번까지 8주내로 진행 
- 각 기능별 세부적인 마일스톤은 각 파트별 판단하에 진행 
- 빨리 개발이 끝나면 다음단계 먼저 진행해도 무방
